### ISSUE TITLE
Ultimo 4k crash OpenAtv 6.3

### ISSUE THREAD

**Issue by Gerry55** [KravenHD/KravenFHD#4]
I have used OpenATV 6.3 with your wonderful skin kravanFHD fore a while without problem, but after an OpenATV firmware update, the image crashes every time I attempt to play any 4k channel!

The OpenATV forum suggested that I contact you for a fix

My receiver is a Vu+ Ultimo 4k

Regards
Gerry

openATV Enigma2 crash log

crashdate=Fri Jan  4 23:02:53 2019
compiledate=Jan  4 2019
skin=KravenFHD/skin.xml
sourcedate=2019-01-03
branch=6.3
rev=2.8.0-19928-g5ec7c7f
component=Enigma2

stbmodel=ultimo4k
stbmodel=dm8000
kernelcmdline=root=/dev/mmcblk0p4 rootfstype=ext4 rootflags=data=journal rootwait rw coherent_pool=2M vmalloc=622m bmem=630m@394m bmem=383m@1665m bmem=443m@2625m
nimsockets=NIM Socket 0:
imageversion=box_type=vuultimo4k
imageissue=Welcome to openATV for %h

31 <   > dvb/decoder.cpp:464 freeze [eDVBVideo0] VIDEO_FREEZE ok
23:02:31.6968 <   > dvb/decoder.cpp:418 startPid [eDVBVideo0] VIDEO_PLAY ok
23:02:31.7058 <   > dvb/decoder.cpp:488 setSlowMotion [eDVBVideo0] VIDEO_SLOWMOTION 0 ok
23:02:31.7100 <   > dvb/decoder.cpp:503 setFastForward [eDVBVideo0] VIDEO_FAST_FORWARD 0 ok
23:02:31.7145 <   > dvb/decoder.cpp:476 unfreeze [eDVBVideo0] VIDEO_CONTINUE ok
23:02:31.7184 <   > dvb/decoder.cpp:207 unfreeze [eDVBAudio0] AUDIO_CONTINUE ok
23:02:31.7272 [   ] dvb/teletext.cpp:222 eDVBTeletextParser [eDVBTeletextParser] Starting!
23:02:31.7272 [   ] dvb/teletext.cpp:645 setPageAndMagazine [eDVBTeletextParser] disable teletext subtitles page ffffffffffffffff (und)
23:02:31.7273 [!W!] dvb/demux.cpp:361 eDVBPESReader [eDVBPESReader] Created. Opening demux
23:02:31.7273 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
23:02:31.7274 [   ] dvb/teletext.cpp:230 eDVBTeletextParser [eDVBTeletextParser] created teletext subtitle PES reader!
23:02:31.7274 [!W!] dvb/demux.cpp:361 eDVBPESReader [eDVBPESReader] Created. Opening demux
23:02:31.7275 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
23:02:31.7276 [   ] dvb/teletext.cpp:463 start [eDVBTeletextParser] starting PES reader on pid=ffffffff
23:02:31.7280 [   ] service/servicedvb.cpp:1743 timeshift [eDVBServicePlay] timeshift
23:02:31.7284 [   ] service/servicedvb.cpp:1743 timeshift [eDVBServicePlay] timeshift
23:02:31.7286 [   ] service/servicedvb.cpp:1743 timeshift [eDVBServicePlay] timeshift
23:02:31.7292 { E } Components/Pixmap.py:133 setPixmapNum setPixmapNum(0) failed! defined pixmaps: []
23:02:31.7294 [   ] service/servicedvb.cpp:1743 timeshift [eDVBServicePlay] timeshift
23:02:31.7297 [   ] service/servicedvb.cpp:1743 timeshift [eDVBServicePlay] timeshift
23:02:31.8200 { D } Traceback (most recent call last):
23:02:31.8201 { D }   File "/usr/lib/enigma2/python/Navigation.py", line 249, in dispatchEvent
23:02:31.8203 { D }   File "/usr/lib/enigma2/python/Components/PerServiceDisplay.py", line 17, in event
23:02:31.8205 { D }   File "/usr/lib/enigma2/python/Components/Sources/CurrentService.py", line 27, in serviceEvent
23:02:31.8206 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
23:02:31.8210 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
23:02:31.8212 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 248, in changed
23:02:31.8220 { D }     Converter.changed(self, what)
23:02:31.8220 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
23:02:31.8222 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
23:02:31.8223 { D }   File "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 24, in changed
23:02:31.8224 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
23:02:31.8225 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 205, in getText
23:02:31.8227 { D }     return self.createVideoCodec(info) + ", " + self.createResolution(info) + ", " + self.createFrameRate(info) + " fps"
23:02:31.8227 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 61, in createVideoCodec
23:02:31.8229 { D }     return ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "")[info.getInfo(iServiceInformation.sVideoType)]
23:02:31.8230 { D } IndexError: tuple index out of range
23:02:31.8230 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation instance at 0x8fd94dc8>>,(5,)) failed)
23:02:33.2753 [   ] dvb/epgcache.cpp:1599 startEPG [eEPGCache] start caching events(1546642953)
23:02:33.2754 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=3842
23:02:33.2758 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=3003
23:02:33.2762 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=18
23:02:33.2768 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=18
23:02:33.2777 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=18
23:02:33.2788 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=5000
23:02:33.2791 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=5000
23:02:33.2796 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=57
23:02:35.0521 [   ] gdi/grc.cpp:211 thread [gRC] main thread is non-idle! display spinner!
23:02:40.2801 [   ] dvb/epgcache.cpp:1948 abortNonAvail [eEPGCache] abort non avail nownext reading
23:02:40.2813 [   ] dvb/epgcache.cpp:1955 abortNonAvail [eEPGCache] abort non avail schedule reading
23:02:40.2820 [   ] dvb/epgcache.cpp:1962 abortNonAvail [eEPGCache] abort non avail schedule other reading
23:02:40.2824 [   ] dvb/epgcache.cpp:1986 abortNonAvail [eEPGCache] abort non avail netmed schedule reading
23:02:40.2828 [   ] dvb/epgcache.cpp:1993 abortNonAvail [eEPGCache] abort non avail netmed schedule other reading
23:02:40.2829 [   ] dvb/epgcache.cpp:2013 abortNonAvail [eEPGCache] abort non avail viasat reading
23:02:41.8348 {   } Components/StackTrace.py:33 run StackTrace
23:02:41.9240 { D } Traceback (most recent call last):
23:02:41.9241 { D }   File "/usr/lib/enigma2/python/Navigation.py", line 249, in dispatchEvent
23:02:41.9242 { D }   File "/usr/lib/enigma2/python/Components/PerServiceDisplay.py", line 17, in event
23:02:41.9244 { D }   File "/usr/lib/enigma2/python/Components/Sources/CurrentService.py", line 27, in serviceEvent
23:02:41.9245 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
23:02:41.9246 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
23:02:41.9247 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 248, in changed
23:02:41.9249 { D }     Converter.changed(self, what)
23:02:41.9249 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
23:02:41.9251 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
23:02:41.9252 { D }   File "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 24, in changed
23:02:41.9253 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
23:02:41.9254 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 205, in getText
23:02:41.9255 { D }     return self.createVideoCodec(info) + ", " + self.createResolution(info) + ", " + self.createFrameRate(info) + " fps"
23:02:41.9256 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 61, in createVideoCodec
23:02:41.9257 { D }     return ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "")[info.getInfo(iServiceInformation.sVideoType)]
23:02:41.9259 { D } IndexError: tuple index out of range
23:02:41.9260 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation instance at 0x8fd94dc8>>,(6,)) failed)
23:02:42.9264 [   ] dvb/cahandler.cpp:267 registerService [eDVBCAService] new service 1:0:1F:1CE8:7F6:2:11A0000:0:0:0:
23:02:42.9265 [   ] dvb/cahandler.cpp:285 registerService [eDVBCAService] add demux 0 to slot 0 service 1:0:1F:1CE8:7F6:2:11A0000:0:0:0:
23:02:42.9267 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
23:02:42.9267 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=257
23:02:42.9284 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
23:02:42.9284 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=32
23:02:42.9288 [   ] dvb/frontend.cpp:2411 tuneLoopInt [SEC] set dynamic current limiting
23:02:42.9295 { D } Traceback (most recent call last):
23:02:42.9296 { D }   File "/usr/lib/enigma2/python/Components/Converter/Poll.py", line 25, in poll
23:02:42.9298 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 251, in changed
23:02:42.9300 { D }     Converter.changed(self, what)
23:02:42.9301 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
23:02:42.9302 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
23:02:42.9303 { D }   File "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 24, in changed
23:02:42.9304 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
23:02:42.9305 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 205, in getText
23:02:42.9307 { D }     return self.createVideoCodec(info) + ", " + self.createResolution(info) + ", " + self.createFrameRate(info) + " fps"
23:02:42.9307 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 61, in createVideoCodec
23:02:42.9308 { D }     return ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "")[info.getInfo(iServiceInformation.sVideoType)]
23:02:42.9309 { D } IndexError: tuple index out of range
23:02:42.9310 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method KravenFHDExtraInfo.poll of <class 'Components.Converter.KravenFHDExtraInfo.KravenFHDExtraInfo'>(VideoInfo)>,()) failed)
23:02:43.9383 [   ] gdi/grc.cpp:211 thread [gRC] main thread is non-idle! display spinner!
23:02:45.9823 [   ] gdi/grc.cpp:211 thread [gRC] main thread is non-idle! display spinner!
23:02:52.9523 {   } Components/StackTrace.py:49 run ========== Stacktrace of active Python threads ===========
23:02:52.9524 {   } Components/StackTrace.py:49 run ========== Thread ID  0x-73ebdc00 =========================
23:02:52.9525 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
23:02:52.9525 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
23:02:52.9526 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 754, in run
23:02:52.9527 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 45, in work
23:02:52.9527 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/Queue.py", line 168, in get
23:02:52.9528 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 340, in wait
23:02:52.9529 {   } Components/StackTrace.py:49 run ========== Thread ID  0x-71508c00 =========================
23:02:52.9529 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
23:02:52.9530 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
23:02:52.9531 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Plugins/Extensions/WebkitHbbTV/vbipc.py", line 114, in run
23:02:52.9531 { E } Components/StackTrace.py:49 run   readable, writable, errored = select.select([self.mSock], [], [], self.mTimeout)
23:02:52.9532 {   } Components/StackTrace.py:49 run ========== MainThread 0x-4aa1bff0 =========================
23:02:52.9533 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 869, in <module>
23:02:52.9533 {   } Components/StackTrace.py:49 run   runScreenTest()
23:02:52.9534 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 640, in runScreenTest
23:02:52.9535 {   } Components/StackTrace.py:49 run   runReactor()
23:02:52.9535 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 122, in runReactor
23:02:52.9536 {   } Components/StackTrace.py:49 run   reactor.run(installSignalHandlers=False)
23:02:52.9537 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
23:02:52.9537 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1273, in mainLoop
23:02:52.9538 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/e2reactor.py", line 150, in doPoll
23:02:52.9538 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/e2reactor.py", line 40, in poll
23:02:52.9539 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Navigation.py", line 249, in dispatchEvent
23:02:52.9540 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/PerServiceDisplay.py", line 17, in event
23:02:52.9540 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Sources/CurrentService.py", line 27, in serviceEvent
23:02:52.9541 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
23:02:52.9542 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
23:02:52.9543 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Element.py", line 87, in changed
23:02:52.9543 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
23:02:52.9544 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 27, in changed
23:02:52.9545 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Element.py", line 16, in wrapper
23:02:52.9545 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Converter/KravenFHDTextTranslator.py", line 178, in getText
23:02:52.9546 {   } Components/StackTrace.py:49 run   return _('video') + ":"
23:02:52.9546 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Converter/KravenFHDTextTranslator.py", line 15, in _
23:02:52.9547 {   } Components/StackTrace.py:49 run   t = gettext.dgettext("KravenFHD", txt)
23:02:52.9548 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/gettext.py", line 701, in dgettext
23:02:52.9548 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/gettext.py", line 636, in translation
23:02:52.9549 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/gettext.py", line 620, in find
23:02:52.9550 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/genericpath.py", line 28, in exists
23:02:52.9550 {   } Components/StackTrace.py:49 run ========== Stacktrace end ================================
23:02:52.9631 {   } skin.py:1375 readSkin [SKIN] processing screen MessageBox:
23:02:52.9792 {   } skin.py:1375 readSkin [SKIN] processing screen MessageBox_summary:
23:02:52.9807 {   } Screens/Screen.py:150 show [SCREENNAME]  ['MessageBox_summary', 'SimpleSummary']
23:02:52.9811 {   } Screens/Screen.py:150 show [SCREENNAME]  ['MessageBox']
23:02:53.0490 { D } Traceback (most recent call last):
23:02:53.0492 { D }   File "/usr/lib/enigma2/python/Components/Converter/Poll.py", line 25, in poll
23:02:53.0494 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 251, in changed
23:02:53.0496 { D }     Converter.changed(self, what)
23:02:53.0500 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
23:02:53.0511 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
23:02:53.0513 { D }   File "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 24, in changed
23:02:53.0514 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
23:02:53.0515 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 205, in getText
23:02:53.0517 { D }     return self.createVideoCodec(info) + ", " + self.createResolution(info) + ", " + self.createFrameRate(info) + " fps"
23:02:53.0518 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDExtraInfo.py", line 61, in createVideoCodec
23:02:53.0519 { D }     return ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "")[info.getInfo(iServiceInformation.sVideoType)]
23:02:53.0520 { D } IndexError: tuple index out of range
23:02:53.0522 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method KravenFHDExtraInfo.poll of <class 'Components.Converter.KravenFHDExtraInfo.KravenFHDExtraInfo'>(VideoInfo)>,()) failed)

dmesg

**Comment by ghost** [comment]
fixed
