### ISSUE TITLE
still crashing 4k Openatv

### ISSUE THREAD

**Issue by Gerry55** [KravenHD/KravenFHD#5]
After your fix for the OpenAtv 6.3 crashing on a 4k channel, I installed your master file fix, but it still crashes after a reboot when put onto a 4k channel.

Though I think it takes a little longer to crash now.
Thanks for your prompt attention!
New crash log
openATV Enigma2 crash log

crashdate=Sun Jan  6 11:28:59 2019
compiledate=Jan  4 2019
skin=KravenFHD/skin.xml
sourcedate=2019-01-03
branch=6.3
rev=2.8.0-19928-g5ec7c7f
component=Enigma2

stbmodel=ultimo4k
stbmodel=dm8000
kernelcmdline=root=/dev/mmcblk0p4 rootfstype=ext4 rootflags=data=journal rootwait rw coherent_pool=2M vmalloc=622m bmem=630m@394m bmem=383m@1665m bmem=443m@2625m
nimsockets=NIM Socket 0:
imageversion=box_type=vuultimo4k
imageissue=Welcome to openATV for %h

Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 340, in wait
11:28:25.0164 {   } Components/StackTrace.py:49 run ========== Thread ID  0x-7141bc00 =========================
11:28:25.0164 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
11:28:25.0165 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
11:28:25.0166 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Plugins/Extensions/WebkitHbbTV/vbipc.py", line 114, in run
11:28:25.0166 { E } Components/StackTrace.py:49 run   readable, writable, errored = select.select([self.mSock], [], [], self.mTimeout)
11:28:25.0167 {   } Components/StackTrace.py:49 run ========== MainThread 0x-4a9a5ff0 =========================
11:28:25.0168 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 869, in <module>
11:28:25.0168 {   } Components/StackTrace.py:49 run   runScreenTest()
11:28:25.0169 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 640, in runScreenTest
11:28:25.0169 {   } Components/StackTrace.py:49 run   runReactor()
11:28:25.0170 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 122, in runReactor
11:28:25.0171 {   } Components/StackTrace.py:49 run   reactor.run(installSignalHandlers=False)
11:28:25.0171 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
11:28:25.0172 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1273, in mainLoop
11:28:25.0173 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/e2reactor.py", line 150, in doPoll
11:28:25.0173 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/e2reactor.py", line 40, in poll
11:28:25.0174 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Navigation.py", line 249, in dispatchEvent
11:28:25.0175 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/PerServiceDisplay.py", line 17, in event
11:28:25.0175 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Sources/CurrentService.py", line 27, in serviceEvent
11:28:25.0176 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
11:28:25.0177 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
11:28:25.0177 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Element.py", line 87, in changed
11:28:25.0178 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
11:28:25.0179 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 27, in changed
11:28:25.0179 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Element.py", line 16, in wrapper
11:28:25.0180 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Converter/KravenFHDTextTranslator.py", line 182, in getText
11:28:25.0180 {   } Components/StackTrace.py:49 run   return _('Flash:')
11:28:25.0181 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/Converter/KravenFHDTextTranslator.py", line 15, in _
11:28:25.0182 {   } Components/StackTrace.py:49 run   t = gettext.dgettext("KravenFHD", txt)
11:28:25.0182 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/gettext.py", line 701, in dgettext
11:28:25.0183 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/gettext.py", line 636, in translation
11:28:25.0184 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/gettext.py", line 620, in find
11:28:25.0184 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/genericpath.py", line 28, in exists
11:28:25.0185 {   } Components/StackTrace.py:49 run ========== Stacktrace end ================================
11:28:25.1340 [   ] dvb/cahandler.cpp:267 registerService [eDVBCAService] new service 1:0:1F:1CE8:7F6:2:11A0000:0:0:0:
11:28:25.1341 [   ] dvb/cahandler.cpp:285 registerService [eDVBCAService] add demux 0 to slot 0 service 1:0:1F:1CE8:7F6:2:11A0000:0:0:0:
11:28:25.1350 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
11:28:25.1351 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=257
11:28:25.1365 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
11:28:25.1366 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=32
11:28:25.1419 { D } Traceback (most recent call last):
11:28:25.1420 { D }   File "/usr/lib/enigma2/python/Components/Converter/Poll.py", line 25, in poll
11:28:25.1422 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDServiceInfoEX.py", line 366, in changed
11:28:25.1426 { D }     Converter.changed(self, what)
11:28:25.1426 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
11:28:25.1428 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
11:28:25.1429 { D }   File "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 24, in changed
11:28:25.1430 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
11:28:25.1431 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDServiceInfoEX.py", line 215, in getText
11:28:25.1433 { D }     self.stream['vtype'] = ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "")[info.getInfo(iServiceInformation.sVideoType)]
11:28:25.1434 { D } IndexError: tuple index out of range
11:28:25.1434 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method KravenFHDServiceInfoEX.poll of <class 'Components.Converter.KravenFHDServiceInfoEX.KravenFHDServiceInfoEX'>(Resolution)>,()) failed)
11:28:26.2808 {   } skin.py:1375 readSkin [SKIN] processing screen MessageBox:
11:28:26.3015 {   } skin.py:1375 readSkin [SKIN] processing screen MessageBox_summary:
11:28:26.3033 {   } Screens/Screen.py:150 show [SCREENNAME]  ['MessageBox_summary', 'SimpleSummary']
11:28:26.3037 {   } Screens/Screen.py:150 show [SCREENNAME]  ['MessageBox']
11:28:26.8944 [   ] dvb/demux.cpp:90 openDemux [eDVBDemux] open demux /dev/dvb/adapter0/demux0
11:28:26.8945 [   ] dvb/demux.cpp:286 start [eDVBSectionReader] DMX_SET_FILTER pid=256
11:28:26.9170 [   ] dvb/pmt.cpp:998 SDTScanEvent [eDVBServicePMTHandler] sdt update done!
11:28:26.9171 <   > dvb/decoder.cpp:547 video_event [eDVBVideo0] VIDEO_GET_EVENT SIZE_CHANGED 3840x2160 aspect 3

11:28:26.9295 { D } Traceback (most recent call last):
11:28:26.9295 { D }   File "/usr/lib/enigma2/python/Navigation.py", line 249, in dispatchEvent
11:28:26.9297 { D }   File "/usr/lib/enigma2/python/Components/PerServiceDisplay.py", line 17, in event
11:28:26.9298 { D }   File "/usr/lib/enigma2/python/Components/Sources/CurrentService.py", line 27, in serviceEvent
11:28:26.9299 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
11:28:26.9300 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
11:28:26.9301 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDServiceInfoEX.py", line 364, in changed
11:28:26.9304 { D }     Converter.changed(self, what)
11:28:26.9305 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
11:28:26.9306 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
11:28:26.9307 { D }   File "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 24, in changed
11:28:26.9308 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
11:28:26.9309 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDServiceInfoEX.py", line 215, in getText
11:28:26.9311 { D }     self.stream['vtype'] = ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "")[info.getInfo(iServiceInformation.sVideoType)]
11:28:26.9312 { D } IndexError: tuple index out of range
11:28:26.9313 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method Navigation.dispatchEvent of <Navigation.Navigation instance at 0x8fdc2080>>,(15,)) failed)
11:28:29.1713 [   ] gdi/grc.cpp:211 thread [gRC] main thread is non-idle! display spinner!
11:28:36.9362 <   > dvb/decoder.cpp:547 video_event [eDVBVideo0] VIDEO_GET_EVENT FRAME_RATE_CHANGED 50000 fps

11:28:36.9370 {   } Components/StackTrace.py:33 run StackTrace
11:28:36.9383 <   > dvb/decoder.cpp:547 video_event [eDVBVideo0] VIDEO_GET_EVENT PROGRESSIVE_CHANGED 1

11:28:36.9409 {   } Components/StackTrace.py:49 run ========== Stacktrace of active Python threads ===========
11:28:36.9411 {   } Components/StackTrace.py:49 run ========== Thread ID  0x-7b900c00 =========================
11:28:36.9411 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
11:28:36.9412 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
11:28:36.9413 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 754, in run
11:28:36.9413 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 45, in work
11:28:36.9414 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/Queue.py", line 168, in get
11:28:36.9415 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 340, in wait
11:28:36.9415 {   } Components/StackTrace.py:49 run ========== Thread ID  0x-74434c00 =========================
11:28:36.9416 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
11:28:36.9417 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
11:28:36.9417 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 754, in run
11:28:36.9418 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 45, in work
11:28:36.9419 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/Queue.py", line 168, in get
11:28:36.9419 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 340, in wait
11:28:36.9420 {   } Components/StackTrace.py:49 run ========== Thread ID  0x-7141bc00 =========================
11:28:36.9420 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 774, in __bootstrap
11:28:36.9421 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
11:28:36.9422 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Plugins/Extensions/WebkitHbbTV/vbipc.py", line 114, in run
11:28:36.9423 { E } Components/StackTrace.py:49 run   readable, writable, errored = select.select([self.mSock], [], [], self.mTimeout)
11:28:36.9423 {   } Components/StackTrace.py:49 run ========== MainThread 0x-4a9a5ff0 =========================
11:28:36.9424 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 869, in <module>
11:28:36.9424 {   } Components/StackTrace.py:49 run   runScreenTest()
11:28:36.9425 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 640, in runScreenTest
11:28:36.9426 {   } Components/StackTrace.py:49 run   runReactor()
11:28:36.9426 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/mytest.py", line 122, in runReactor
11:28:36.9427 {   } Components/StackTrace.py:49 run   reactor.run(installSignalHandlers=False)
11:28:36.9428 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1261, in run
11:28:36.9428 {   } Components/StackTrace.py:49 run File: "/usr/lib/python2.7/site-packages/twisted/internet/base.py", line 1273, in mainLoop
11:28:36.9429 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/e2reactor.py", line 150, in doPoll
11:28:36.9430 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/e2reactor.py", line 40, in poll
11:28:36.9430 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Navigation.py", line 253, in dispatchEvent
11:28:36.9431 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Components/ServiceEventTracker.py", line 80, in event
11:28:36.9431 {   } Components/StackTrace.py:49 run File: "/usr/lib/enigma2/python/Screens/VideoMode.py", line 657, in VideoChanged
11:28:36.9432 {   } Components/StackTrace.py:49 run ========== Stacktrace end ================================
11:28:37.1558 [   ] base/console.cpp:110 execute [eConsoleAppContainer] Starting sdparm
11:28:37.7525 [   ] base/ebase.cpp:279 processOneEvent [eMainloop::processOneEvent] unhandled POLLERR/HUP/NVAL for fd 90(16)
11:28:41.4255 [   ] dvb/dvbtime.cpp:468 updateTime [eDVBLocalTimerHandler] Transponder time is 06.01.2019 11:28:41
11:28:41.4256 [   ] dvb/dvbtime.cpp:481 updateTime [eDVBLocalTimerHandler] diff is 0
11:28:41.4256 [   ] dvb/dvbtime.cpp:484 updateTime [eDVBLocalTimerHandler] diff < 120 .. use Transponder Time
11:28:41.4256 [   ] dvb/dvbtime.cpp:545 updateTime [eDVBLocalTimerHandler] not changed
11:28:41.4260 [   ] dvb/dvb.cpp:2419 getDemux [eDVBChannel] getDemux cap=00
11:28:59.7989 [   ] driver/rcinput.cpp:38 handleCode [eRCDeviceInputDev] 1 160 1
11:28:59.8019 {   } Screens/InfoBarGenerics.py:205 actionA KEY: 352 0 KEY_OK OK
11:28:59.8022 {   } Components/ActionMap.py:46 action action ->  MsgBoxActions ok
11:28:59.8041 {   } Screens/Screen.py:150 show [SCREENNAME]  InfoBarSummary
11:28:59.8135 {   } Screens/Screen.py:150 show [SCREENNAME]  InfoBar
11:28:59.8140 [   ] service/servicedvb.cpp:1743 timeshift [eDVBServicePlay] timeshift
11:28:59.8184 { D } Traceback (most recent call last):
11:28:59.8184 { D }   File "/usr/lib/enigma2/python/mytest.py", line 231, in processDelay
11:28:59.8187 { D }     self.popCurrent()
11:28:59.8187 { D }   File "/usr/lib/enigma2/python/mytest.py", line 305, in popCurrent
11:28:59.8189 { D }     self.execBegin(first=False, do_show=do_show)
11:28:59.8190 { D }   File "/usr/lib/enigma2/python/mytest.py", line 250, in execBegin
11:28:59.8192 { D }     c.show()
11:28:59.8192 { D }   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/AnimationSetup/plugin.py", line 220, in screen_show
11:28:59.8195 { D }   File "/usr/lib/enigma2/python/Screens/Screen.py", line 160, in show
11:28:59.8196 { D }   File "/usr/lib/enigma2/python/Components/Renderer/Renderer.py", line 10, in onShow
11:28:59.8198 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 99, in setSuspend
11:28:59.8199 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 104, in checkSuspend
11:28:59.8200 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 94, in setSuspend
11:28:59.8201 { D }   File "/usr/lib/enigma2/python/Components/Converter/Poll.py", line 32, in doSuspend
11:28:59.8202 { D }   File "/usr/lib/enigma2/python/Components/Converter/Poll.py", line 25, in poll
11:28:59.8203 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDServiceInfoEX.py", line 366, in changed
11:28:59.8206 { D }     Converter.changed(self, what)
11:28:59.8206 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 86, in changed
11:28:59.8207 { D }   File "/usr/lib/enigma2/python/Tools/CList.py", line 7, in __call__
11:28:59.8208 { D }   File "/usr/lib/enigma2/python/Components/Renderer/Label.py", line 24, in changed
11:28:59.8210 { D }   File "/usr/lib/enigma2/python/Components/Element.py", line 15, in wrapper
11:28:59.8211 { D }   File "/usr/lib/enigma2/python/Components/Converter/KravenFHDServiceInfoEX.py", line 215, in getText
11:28:59.8212 { D }     self.stream['vtype'] = ("MPEG2", "MPEG4", "MPEG1", "MPEG4-II", "VC1", "VC1-SM", "")[info.getInfo(iServiceInformation.sVideoType)]
11:28:59.8213 { D } IndexError: tuple index out of range
11:28:59.8214 [ E ] python/python.cpp:210 call [ePyObject] (PyObject_CallObject(<bound method Session.processDelay of <__main__.Session instance at 0x8ec088a0>>,()) failed)

**Comment by ghost** [comment]
https://github.com/KravenHD/KravenFHD/issues/4
